server:
  port: 3000

management:
  endpoints:
    web:
      exposure:
        include:
        - info
        - health
        - refresh

info:
  service:
    name: UaaService
    group: introms
    version: 0.1.0
    

spring:
  application:
    name: UaaService
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/introms?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: darkstar
  jpa:
    generate-ddl: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    preferIpAddress: true

default:
  user:
    role: "ROLE_USER"

logging:
  level:
    it.itresources.demo.micro.uaaservice: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE